<a href="https://colab.research.google.com/github/hwang82513/colab/blob/main/b_posco_ipynb%EC%9D%98_%EC%82%AC%EB%B3%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ch4. dataframe

In [ ]:
import pandas as pd
#데이터프레임 생성
data = {'이름':['홍길동','이순신','강감찬','임꺽정','이성계'],'출생년도':[1980,1986,1990,1985,1988],'점수':[1.5,1.7,3.6,2.4,2.9]}
df =pd.DataFrame(data)
df

    이름  출생년도   점수
0  홍길동  1980  1.5
1  이순신  1986  1.7
2  강감찬  1990  3.6
3  임꺽정  1985  2.4
4  이성계  1988  2.9

In [ ]:

#데이터프레임 열이름 변경하기
df = df.rename({'출생년도':'출생'}, axis='columns')
df

    이름    출생   점수
0  홍길동  1980  1.5
1  이순신  1986  1.7
2  강감찬  1990  3.6
3  임꺽정  1985  2.4
4  이성계  1988  2.9

In [ ]:

#데이터프레임 열 데이터 가져오기
df[['이름','출생']]
df.이름

0    홍길동
1    이순신
2    강감찬
3    임꺽정
4    이성계
Name: 이름, dtype: object

In [ ]:

#데이터프레임 행 데이터 가져오기
df[1:3]

    이름    출생   점수
1  이순신  1986  1.7
2  강감찬  1990  3.6

In [ ]:
# loc[]과 iloc[]
df.loc[0:1,['이름','출생']] # 행열 이름으로 범위지정, 이름이 없으면 인덱스로 지정
df.iloc[0:2,0:2] # 인덱스 번호로 선택

    이름    출생
0  홍길동  1980
1  이순신  1986

In [ ]:
# 열추가와 삭제
df['보너스']=df['점수']*5 #보너스 열 추가
df

    이름    출생   점수   보너스
0  홍길동  1980  1.5   7.5
1  이순신  1986  1.7   8.5
2  강감찬  1990  3.6  18.0
3  임꺽정  1985  2.4  12.0
4  이성계  1988  2.9  14.5

In [ ]:
df['지역']=['서울','서울','부산','대구','인천'] # 지역 열 추가
df

    이름    출생   점수   보너스  지역
0  홍길동  1980  1.5   7.5  서울
1  이순신  1986  1.7   8.5  서울
2  강감찬  1990  3.6  18.0  부산
3  임꺽정  1985  2.4  12.0  대구
4  이성계  1988  2.9  14.5  인천

In [ ]:
del df['보너스'] # 보너스 열 삭제
df

    이름    출생   점수  지역
0  홍길동  1980  1.5  서울
1  이순신  1986  1.7  서울
2  강감찬  1990  3.6  부산
3  임꺽정  1985  2.4  대구
4  이성계  1988  2.9  인천

In [ ]:
df.loc[5] = ['김순신', 1980,3.3,'광주'] #행추가
df

    이름    출생   점수  지역
0  홍길동  1980  1.5  서울
1  이순신  1986  1.7  서울
2  강감찬  1990  3.6  부산
3  임꺽정  1985  2.4  대구
4  이성계  1988  2.9  인천
5  김순신  1980  3.3  광주

In [ ]:
df.iloc[4,1]

1988